CREATE TABLE BOARD
(
  SEQ NUMBER(5) PRIMARY KEY,
  GRP_SEQ NUMBER(5),
  PARENT_SEQ NUMBER(5),
  TITLE VARCHAR2(100),
  INSERT_TIME VARCHAR2(14),
  INSERT_ID VARCHAR2(30),
  READ_COUNT NUMBER(5)
)

SELECT LEVEL, A.*
FROM BOARD A
START WITH PARENT_SEQ = 0
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER SIBLINGS BY GRP_SEQ DESC;