CREATE TABLE BOARD
(
  SEQ NUMBER(5) PRIMARY KEY,
  GRP_SEQ NUMBER(5),
  PARENT_SEQ NUMBER(5),
  TITLE VARCHAR2(100),
  INSERT_TIME VARCHAR2(14),
  INSERT_ID VARCHAR2(30),
  READ_COUNT NUMBER(5)
)

SELECT LEVEL, A.*
FROM BOARD A
START WITH PARENT_SEQ = 0
CONNECT BY PRIOR SEQ = PARENT_SEQ
ORDER SIBLINGS BY GRP_SEQ DESC;


CREATE TABLE P_USER_INFO
(
  SEQ NUMBER(8),
  ID   VARCHAR2(50) NOT NULL UNIQUE,
  CSEQ VARCHAR2(10),
  PASSWD VARCHAR2(300) NOT NULL,
  MNAME VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(300) NOT NULL,
  ZIP VARCHAR2(10) NOT NULL,
  TEL VARCHAR2(14) NOT NULL,
  EMAIL VARCHAR2(300) UNIQUE,
  CLEVEL VARCHAR2(2) NOT NULL,
  CDATE DATE NOT NULL,
  USE_FLAG NUMBER(1) DEFAULT '1',
  EN_LAN VARCHAR2(5),
  PRIMARY KEY(CSEQ)
);
INSERT INTO P_USER_INFO VALUES(1,'admin','admin','11','관리자','주소','12345','010-123-456','aa@nate.com','1',SYSDATE,'1','KO');